### ISSUE TITLE
Create collections_seeds.csv file

### ISSUE THREAD

**Issue by jasoncorum** [WGBH/transcript-editor#3]
The rake process for importing webvtt files requires a collection be defined on transcripts in the webvtt import rake task. These are imported using collections_seeds.csv. Required attributes are uid and title. uid should match the collection on the transcripts_seeds.csv file.

- [x] **Done When** a collections_seeds.csv file is created for our initial import.
- [ ] **Done When** the collections dropdown can handle a longer list.

**Comment by jasoncorum** [comment]
Note: In loading the Collections we found that the Collections dropdown on the site doesn't scroll. Adding an additional done when for addressing the UI issue.

**Comment by jasoncorum** [comment]
@sroosa - does this look OK for Collections scroll?

![screen shot 2018-02-14 at 9 35 35 am](https://user-images.githubusercontent.com/3814190/36209718-89ecf5d8-116a-11e8-9000-5b83a47db26e.png)

**Comment by sroosa** [comment]
@jasoncorum yes!
