### ISSUE TITLE
Add checkmark icon to indicate a transcript is completed

### ISSUE THREAD

**Issue by sroosa** [WGBH/transcript-editor#57]
Checkmark shows up on tiles on the index page, and somewhere on the transcript show page too.

**Comment by foglabs** [comment]
Here's a shot at it:
![screen shot 2018-11-14 at 4 29 33 pm](https://user-images.githubusercontent.com/8140840/48514404-3dedcd80-e82c-11e8-99b8-4693d668567d.png)

**Comment by sroosa** [comment]
@foglabs for the transcript show page, can we have a modal or something open whenever someone gets to that page (through clicking from the index page or coming from a direct link they found somewhere else like social media)?
The modal should say:
Great news! This transcript has already been completely corrected! Help us correct another transcript here [link to the index page filtered to the same collection as the transcript who's page they are on]

**Comment by caseyedavis12** [comment]
@foglabs @sroosa In addition to the checkmark, can we provide text next to it like Transcript Completed or something like that?
