### ISSUE TITLE
Create new project with separate IP address for Peabody transcripts

### ISSUE THREAD

**Issue by sroosa** [WGBH/transcript-editor#62]
For the Peabody Collection transcripts, we want a separate project set up where the consensus configuration can be set up differently, there can be different admins, and the IP address is different. We want to keep it at some kind of wonky address, because we only really want the Peabody project volunteers to get to it, not the general public. 

I know the app can handle having multiple projects. However, based on how we want this to work, I'm not sure if it makes more sense to do this as another project within this same app, or if we should have another copy of the app that has the Peabody project and doesn't have the fixit plus project.

**Comment by foglabs** [comment]
added project folder in a branch for this - working to adapt transcript-editor's ansible playbook to amazon linux 2 (as was done for aapb)
